#!/usr/bin/env bash

# Install nginx
apt-get update
apt-get -y install nginx

# Configure nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart nginx without using systemctl
kill -HUP $(pgrep nginx)

# Create index.html with "Hello World!"
echo "Hello World!" > /usr/share/nginx/html/index.html

# Check if nginx is running
if pgrep -x "nginx" >/dev/null; then
    echo "Nginx installed and configured successfully."
else
    echo "Something went wrong with the Nginx installation/configuration."
fi

