#!/usr/bin/env bash

# updates the package lists for available software packages.
apt-get update
# installs the Nginx web server.
apt-get install -y nginx

# Creates the document root directory for Nginx and sets permissions.
mkdir -p /etc/nginx/html
chmod 755 /etc/nginx/html

# Creates the index.html file inside the document root directory.
echo "Hello World!" > /etc/nginx/html/index.html

# Configures the default server block for serving static content.
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /etc/nginx/html;
    index index.html index.htm;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Configures a new server block for redirection.
cat > /etc/nginx/sites-available/redirect <<EOF
server {
    listen 80;
    listen [::]:80;

    root /var/www/html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Enable the new site configuration by creating a symbolic link.
ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Test Nginx configuration and reload.
nginx -t
service nginx reload

