#!/usr/bin/env bash

# Install Nginx (if not installed)
apt-get update
apt-get -y install nginx

# Configure Nginx redirection
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restart Nginx to apply the changes
kill -HUP $(pgrep nginx)

echo "Nginx configured for redirection from /redirect_me."

