#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get -y install nginx

# Create a custom 404 error page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Configure Nginx to use the custom 404 page
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /usr/share/nginx/html;
    index index.html index.htm;

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restart Nginx
kill -HUP $(pgrep nginx)

echo "Nginx configured with a custom 404 page."

