#!/usr/bin/env bash
# This script installs and configures HAProxy as a load balancer

# Install HAProxy if not already installed
if ! command -v haproxy &> /dev/null; then
    sudo apt-get update
    sudo apt-get install -y haproxy
fi

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-02 52.86.195.171:80 check
    server web-01 52.3.240.175:80 check
EOF

# Restart HAProxy service
sudo systemctl restart haproxy
