#!/usr/bin/env bash
# Script to configure Nginx to listen on port 80

# Ensure Nginx is installed
sudo apt-get update
sudo apt-get install nginx -y

# Edit the default Nginx configuration file to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80 default_server;\n\tlisten [::]:80 default_server;/' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

